# Site settings
title: Burgermenu
email: kespers@gmail.com
description: >
  BurgerMenu is a simple off canvas menu with hardware accelerated css transitions, amazing native behavior and compatibility from IE >=8.
baseurl: "/burgermenu"
url: "http://vortizhe.me"

# Build settings
markdown: redcarpet
highlighter: pygments
fenced_code_blocks: true
redcarpet:
 extensions: ["fenced_code_blocks", "tables"]
github: [Repository metadata]

gems:
  - jekyll-sitemap
  - jekyll-feed

# Plugins
sitemap:
  file: "/sitemap.xml"
  exclude:
    - "/feed.xml"
  include_posts:
    - "/index.html"
  change_frequency_name: "change_frequency"
  priority_name: "priority"
