# Site settings
title: Burgermenu
email: kespers@gmail.com
description: >
  BurgerMenu is a simple off canvas menu with hardware accelerated css transitions, amazing native behavior and compatibility from IE >=8.
baseurl: "/burgermenu"
url: "http://vortizhe.me"

# Build settings
github: [Repository metadata]

kramdown:
  hard_wrap: false
  input: GFM

gems:
  - jekyll-sitemap
  - jekyll-feed

# Plugins
sitemap:
  file: "/sitemap.xml"
  exclude:
    - "/feed.xml"
  change_frequency_name: "change_frequency"
  priority_name: "priority"
